# Generated by Django 3.2.5 on 2022-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='tags',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
